### PR TITLE
Replace build system

### PR DESCRIPTION
**Pull request by 4re**
Custom scripts were not that good, you had to add include paths manually to make it work and was full of useless optimizations that were generating slower binaries. Also, installation paths were a mess.

This uses meson, it's clean, easy to maintain and works everywhere.

### CODE REVIEW

**Comment by ghost** [comment]
Fairly sure this will work with meson 0.38.0 as well, just FYI. Not all distros ship something as new as 0.44.0, so you could probably lower that requirement.

**Comment by 4re** [comment]
But it will not, because `cpp_std=c++17` was introduced in `0.44`. To lower that we will have to use `cpp_std=c++1z` but I'm not sure if it is exactly the same, it is?

**Comment by 4re** [comment]
Now I see you actually changed it, that will fail at configure time.

**Comment by dubhater** [comment]
``meson.build:11:0: ERROR:  Native dependency 'fftw3f_threads' not found``

[My fftw package](https://www.archlinux.org/packages/extra/x86_64/fftw/) doesn't include fftw3f_threads.pc. It does have libfftw3f_threads.so. Is this a bug in the distro packaging, the fftw build system, or meson.build?

**Pull request merged**
